### ISSUE TITLE
Take next stage into account for accurate burn time countdown

### ISSUE THREAD

**Issue by Gordon-Dry** [KSPSnark/BetterBurnTime#11]
As KER and MechJeb can take this into account and a KAC alarm represents this, too, I suggest that BBT also does it:

When the actual stage got not enough dV for the whole maneuver burn, the next stage is also taken into account.

**Comment by KSPSnark** [comment]
Thank you for the suggestion, but those are much more complex mods than this one, and I have no plans of putting in the (very large amount of) time needed to add such a feature-- not just implement, but debug and test in every conceivable scenario.  It was quite deliberate that BBT didn't try to do anything with staging.
