### ISSUE TITLE
Rendezvous orbital mechanics bug

### ISSUE THREAD

**Issue by psychonaut25** [KSPSnark/BetterBurnTime#13]
I recently updated from KSP 1.3.1 to 1.7.3, and updated BetterBurnTime accordingly.  However, a strange new bug has appeared in the orbital mechanics during rendezvous with a target vessel.

Just as I reach my closest approach and begin my velocity-matching burn, the game freezes for a moment, and then the target vessel's orbit suddenly changes- it's periapsis drops considerably, to more-or-less the same periapsis as my active vessel, or slightly lower.  My distance to the target vessel also increases, generally by a few kilometers, and my relative velocity drops to only a few meters per second.

I'm not 100% sure this is a bug with BetterBurnTime, but it seems likely given that it always happens just after the three large dots to the right of the navball disappear.

I'm running Windows 7 Professional x64, in case that's of any help.

[Demo Video 1](https://youtu.be/DyDkMJuzfHY)
[Demo Video 2](https://youtu.be/mouRxMwPTDA)
[KSP.log](https://drive.google.com/open?id=1z7hGtC4VFoL7AszkKqY5jG2SNbZEz717)

**Comment by KSPSnark** [comment]
It would be basically impossible for BetterBurnTime to have anything at all to do with this.  BBT never physically _affects_ anything whatsoever.  It _reads_ data (from the current ship, and from the target), and it does calculations, and it _displays_ data... but it has absolutely no physical effect whatsoever and there's not a single line of code in it anywhere that physically modifies any physical object in the game at any time.

There's also the case that nobody else has been reporting this, which I'd expect to see in droves if it were BBT, given how many thousands of people are using it.  So I'd say this is almost certainly some other issue going on, likely another mod.

**Comment by psychonaut25** [comment]
Alright, thanks.  I did notice on the third attempt that it seems to occur when the target vessel enters physics range.  I'll see if anybody on reddit can help out.  Cheers!
