### ISSUE TITLE
API request

### ISSUE THREAD

**Issue by ghost** [KSPSnark/BetterBurnTime#2]
Great mod, thanks!

Is there any chance you could easily write an API that will return the burn time?  My coding abilities are inadequate.  I'd like to try implementing it in RemoteTech to improve the flight computer burn accuracy.

**Comment by KSPSnark** [comment]
Hm, interesting.

If I understand you correctly, you're contributing to RemoteTech and would like to improve its burn accuracy.

This would be a non-trivial task, I think:  BetterBurnTime makes a lot of specific assumptions, including various approximations to avoid hammering the CPU, and so forth, which you might not necessarily want in RemoteTech.  It would mean re-implementing a significantly large fraction of BetterBurnTime inside RemoteTech.

That said, though, there may be some possibilities.  Drop me a PM in the KSP forum and let's chat?

**Comment by KSPSnark** [comment]
Closing the issue-- version 1.5.1 provided a programmatic API, so it's now possible to get numbers out of BetterBurnTime.  See extensive comments in [BetterBurnTimeData.cs](https://github.com/KSPSnark/BetterBurnTime/blob/master/src/BetterBurnTimeData.cs).
